<a href="https://colab.research.google.com/github/Kashaf-Zia06/Python-AI-Bootcamp/blob/main/MachineLearning_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**ENCODING**

In [8]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

#Dummy dataset
df=pd.DataFrame({
    "size":["small","large","medium"],
    "clothes":["shirt","pant","frock"]  #all arrays in dataframe should have same size otherwise error arises
})

print("Original data \n",df)

Original data 
      size clothes
0   small   shirt
1   large    pant
2  medium   frock


In [9]:
le=LabelEncoder()
df["size_label"]=le.fit_transform(df["size"])
print("AFTER ENCODING \n",df)

AFTER ENCODING 
      size clothes  size_label
0   small   shirt           2
1   large    pant           0
2  medium   frock           1


**One hot encoding**

In [10]:
df=pd.DataFrame({
    "color":["red","blue","green"]
})
print("Before one hot encoding\n",df)

Before one hot encoding
    color
0    red
1   blue
2  green


In [11]:
df_onehot=pd.get_dummies(df,columns=["color"]) #get_dummies is used for hot encoding

print("After one hot encoding\n",df_onehot)

After one hot encoding
    color_blue  color_green  color_red
0       False        False       True
1        True        False      False
2       False         True      False


**Feature Scaling**

In [12]:
from sklearn.preprocessing import MinMaxScaler

data={
    "ages":[20,40,50],
    "salaries":[10000,15000,20000]
}

df=pd.DataFrame(data)
print("Before feature scaling normalization\n",df)


Before feature scaling normalization
    ages  salaries
0    20     10000
1    40     15000
2    50     20000


In [19]:
scaler=MinMaxScaler()
df_scaled=scaler.fit_transform(df)
df_scaled=pd.DataFrame(df_scaled,columns=df.columns) #we have to give column name becuase it returns numpy array with column name
print("After scaling:\n",df_scaled)

After scaling:
        ages  salaries
0  0.000000       0.0
1  0.666667       0.5
2  1.000000       1.0


In [22]:
# 📌 Standardization vs Normalization

# 👉 Standardization:
# Standardization transforms data to have:
#   - Mean = 0
#   - Standard Deviation = 1
# It is useful when data follows a Gaussian (normal) distribution.
# Formula: z = (x - mean) / standard_deviation

from sklearn.preprocessing import StandardScaler
import numpy as np

data = np.array([[10], [20], [30], [40], [50]])

scaler = StandardScaler()
standardized_data = scaler.fit_transform(data)

print("Original Data:\n", data.ravel())
print("Standardized Data:\n", standardized_data.ravel())


# 👉 Normalization:
# Normalization rescales data to a fixed range (usually [0,1]).
# It is useful when we want all features on the same scale.
# Formula: x' = (x - min) / (max - min)

from sklearn.preprocessing import MinMaxScaler

normalizer = MinMaxScaler()
normalized_data = normalizer.fit_transform(data)

print("\nOriginal Data:\n", data.ravel())
print("Normalized Data:\n", normalized_data.ravel())


Original Data:
 [10 20 30 40 50]
Standardized Data:
 [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]

Original Data:
 [10 20 30 40 50]
Normalized Data:
 [0.   0.25 0.5  0.75 1.  ]


In [21]:
from sklearn.preprocessing import StandardScaler

sample={
    "marks":[4.5,15,6.3],
    "scores":[4.5,15,6.3]
}

df=pd.DataFrame(sample)
print("Before scaling\n",df)

standard=StandardScaler()

df_standard=pd.DataFrame(standard.fit_transform(df),columns=df.columns)

print("After standardization\n",df_standard)

Before scaling
    marks  scores
0    4.5     4.5
1   15.0    15.0
2    6.3     6.3
After standardization
       marks    scores
0 -0.894268 -0.894268
1  1.395930  1.395930
2 -0.501662 -0.501662
